---
title: "Project Planning"
author: "Jenna"
format: html
editor: visual
---

```{r}

```

## *Data tidying:*

- Join receivers with players.csv to attach player position

## *Question Ideas:*

- What's the most successful play on fourth down?

- Clustering yards after catch & route ran for complete passes, using location of target (x and y coordinates)

- Which team is most successful at converting on fourth down?

```{r}
library(tidyverse)

nfl_passes <- read_csv("https://raw.githubusercontent.com/36-SURE/2026/main/data/nfl_passes.csv")
```

```{r}
# Selecting player position from dataset
players <- players |>
  select(displayName, Position) |>
  arrange(displayName)

# Joins nfl_passes and players dataset to add position of target receivers
data_set <- left_join(nfl_passes, players, by = join_by("target_player_name" == "displayName"))

```

```{r}
nfl_passes |>
  filter(down == 4, !is.na(route_ran)) |>
  ggplot(aes(x = target_x, target_y, color = complete_pass)) +
  geom_point() +
  facet_wrap(~route_ran) +
  coord_flip() +
  theme()
```

```{r}
# Generating dataset with completed passes during fourth down routes
route_outcomes <- data_set |>
  filter(!is.na(Position),
         Position %in% c("RB", "TE", "WR"),
         down == "4"
         ) |>
  group_by(route_ran, Position) |>
  summarise(avg_air_yards = mean(air_yards), avg_total_yards = mean(yards_gained), completed_pass_perc = mean(complete_pass))

# Display dataset
route_outcomes
```

```{r}
# Generates graph to illustrate total yards during fourth down completions based on different routes and positions
route_outcomes |>
  mutate(expected_yards = avg_total_yards * completed_pass_perc) |>
  ggplot(aes(x = route_ran, y = expected_yards)) +
  geom_col() +
   facet_wrap(~Position) +
  coord_flip() 

```

```{r}
library(sportyR)
football_field <- geom_football(league = "NFL", display_range = "in_bounds_only", rotation = 270)

fourth_downs <- nfl_passes |>
  filter(down == 4, !is.na(route_ran)) |>
  group_by(route_ran) |>
  mutate(attempt = n()) |>
  filter(attempt > 10) |>
  ungroup() 

football_field + 
  geom_point(data = fourth_downs, 
             aes(x = target_y -26.65, y = target_x - 60, color = factor(complete_pass))) + 
  facet_wrap(~route_ran) +
  scale_color_manual(
    values = c("0" = "#D9381E", "1" = "lightgreen"), 
    labels = c("0" = "Incomplete", "1" = "Complete"),
    name = "Pass Outcome"
  ) +
  theme_classic()

```

```{r}
nfl_passes |>
  group_by(posteam, route_ran) |>
  summarise(avg_yards = mean(yards_gained)) |>
  ggplot(aes(x = route_ran, y = avg_yards)) +
  geom_col() +
  facet_wrap(~posteam) +
  coord_flip()

nfl_passes |>
  filter(posteam %in% c("KC", "CHI")) |>
  group_by(posteam, route_ran) |>
  summarise(avg_yards = mean(yards_gained), completed_pass_perc = mean(complete_pass), expected_yards = avg_yards * completed_pass_perc) |>
  ggplot(aes(x = route_ran, y = expected_yards)) +
  geom_col() +
  facet_wrap(~posteam) +
  coord_flip()

```

```{r}
summary(nfl_passes$target_x)
summary(nfl_passes$target_y)

```

```{r}
library(nflreadr)
library(ggimage)

player_headshots <- nflreadr::load_rosters(seasons = 2022) 

player_headshots <- player_headshots|>
  select(position, full_name, headshot_url)

df <- nfl_passes |>
  left_join(player_headshots, by = join_by("target_player_name" == "full_name"))

test <- df |>
  group_by(passer_player_name, target_player_name, receiver_headshot = headshot_url, posteam) |>
  summarise(times_targeted = n(), 
            total_yards = sum(yards_gained), 
            yards_per_target = total_yards/times_targeted) |>
  arrange(desc(total_yards)) |>
  filter(times_targeted >= 5) |>
  head(10)

test |>
  ggplot(aes(x = times_targeted, y = total_yards)) +
  geom_image(aes(image = receiver_headshot), size = 0.2) 
  # scale_y_continuous(limits = c(0, 1200))

test |>
  ggplot(aes(x = reorder(target_player_name, total_yards), y = total_yards, fill = posteam)) +
  geom_col(width = 0.52) +
  geom_image(aes(image = receiver_headshot), size = 0.16) +
  coord_flip() +
  theme_classic()
```

```{r}
quarterbacks <- player_headshots |>
  mutate(full_name = str_replace(full_name, "^(\\w)\\w*\\s+", "\\1.")) |>
  select(full_name, qb_headshot = headshot_url)

top_duos <- df |>
  left_join(quarterbacks, by = join_by("passer_player_name" == "full_name"), relationship = "many-to-many") |>
  group_by(passer_player_name, 
           target_player_name, 
           receiver_headshot = headshot_url, 
           qb_headshot,
           posteam) |>
  summarise(times_targeted = n(), 
            total_yards = sum(yards_gained), 
            yards_per_target = total_yards/times_targeted,
            .groups = "drop") |>
  distinct(passer_player_name, target_player_name, .keep_all = TRUE) |>
  arrange(desc(total_yards))|>
  head(10)

top_duos |>
  ggplot(aes(x = reorder(target_player_name, total_yards), 
             y = total_yards, 
             fill = posteam)) +
  geom_col(width = 0.52) +
  geom_image(aes(image = receiver_headshot), size = 0.16) +
  geom_image(aes(y = 0, image = qb_headshot), size = 0.16) +
  scale_y_continuous(breaks = seq(0, 1000, by = 200)) +
  coord_flip() +
  theme_classic()
```
